import { NextRequest, NextResponse } from "next/server";
import type { IAIContent, ISession, INote } from "@/types";

interface GenerateRequestBody {
  title: string;
  date: string;
  location: string;
  description: string;
  sessions: ISession[];
  notes: INote[];
  authorName: string;
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as GenerateRequestBody;
    const { title, date, location, description, sessions, notes, authorName } = body;

    if (!title) {
      return NextResponse.json(
        { error: "Event title is required." },
        { status: 400 }
      );
    }

    // ── Simulate AI inference delay ───────────────────────────
    await new Promise((r) => setTimeout(r, 1200));

    // ── Format date nicely ────────────────────────────────────
    const prettyDate = new Date(date).toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    // ── Build structured session highlights ────────────────────
    const sessionHighlights =
      sessions.length > 0
        ? sessions
            .map(
              (s, i) =>
                `${i + 1}. "${s.title}" by ${s.speaker}${s.takeaway ? `\n   Key insight: ${s.takeaway}` : ""}`
            )
            .join("\n\n")
        : "Sessions to be reviewed.";

    const sessionBullets =
      sessions.length > 0
        ? sessions
            .map((s) => `🔹 "${s.title}" by ${s.speaker} — ${s.takeaway || "Excellent talk"}`)
            .join("\n")
        : "";

    const notesSection =
      notes.length > 0
        ? notes.map((n) => `• ${n.content}`).join("\n")
        : "Personal reflections coming soon.";

    const topTakeaway =
      notes.length > 0 ? notes[0].content : (sessions.length > 0 ? sessions[0].takeaway : "A transformative experience");

    // ── Generate polished, well-structured content ────────────

    const recap = `# ${title} — Event Recap

**${prettyDate} · ${location}**

---

## Overview

${description}

${title} brought together thought leaders, practitioners, and innovators for an outstanding program of sessions and discussions.

## Session Highlights

${sessionHighlights}

## Personal Reflections

${notesSection}

## Key Takeaways

This event underscored the rapid pace of innovation in the industry. The caliber of speakers and depth of content made ${title} a standout event. The insights gained here will directly influence my upcoming projects and strategic thinking.

---

*Recap generated by EventScribe AI*`;

    const linkedInDraft = `I just attended ${title}, and it was genuinely one of the most impactful events I've experienced this year.

📅 ${prettyDate}
📍 ${location}

${description}

${sessions.length > 0 ? `Here are my top takeaways:\n\n${sessionBullets}\n` : ""}
${topTakeaway ? `💡 My biggest insight: ${topTakeaway}\n` : ""}
Events like ${title} remind me why continuous learning isn't optional — it's a competitive advantage. The conversations I had and the ideas I was exposed to have already shifted how I think about my work.

If you attended too, I'd love to hear your highlights! Drop them in the comments 👇

${sessions.length > 0 ? `#${title.replace(/\s+/g, "")} #ProfessionalDevelopment #Learning #Innovation` : `#${title.replace(/\s+/g, "")} #Learning #ProfessionalDevelopment`}

— ${authorName}`;

    const twitterDraft = `🧵 My key takeaways from ${title} (${prettyDate}, ${location}):

${sessions.length > 0
  ? sessions.map((s, i) => `${i + 1}/ ${s.takeaway || `"${s.title}" by ${s.speaker} was outstanding`}`).join("\n\n")
  : "1/ An incredible event packed with actionable insights"}

${sessions.length > 0 ? `${sessions.length + 1}/` : "2/"} Events like ${title} are where the future gets shaped. Grateful for the opportunity to learn from this incredible community.

What were YOUR biggest takeaways? 👇

#${title.replace(/\s+/g, "")}`;

    const aiContent: IAIContent = {
      recap,
      linkedInDraft,
      twitterDraft,
      generatedAt: new Date().toISOString(),
    };

    return NextResponse.json({ aiContent }, { status: 200 });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Internal server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
